version: "3.9"
services:
  pyspawn:
    command: py.test --junitxml=xunit-reports/xunit-result-all.xml --cov --cov-report=xml:coverage-reports/coverage.xml --cov-report=html:coverage-reports/
    volumes:
      - ${SYSTEM_DEFAULTWORKINGDIRECTORY}/xunit-reports/:/app/xunit-reports/
      - ${SYSTEM_DEFAULTWORKINGDIRECTORY}/coverage-reports/:/app/coverage-reports/