---
parameters:
- name: composeArgs
  type: string


steps:
  - task: DockerCompose@0
    displayName: Build services
    inputs:
      action: Build services
      containerregistrytype: Container Registry
      dockerComposeFile: docker-compose.yaml
      additionalDockerComposeFiles: docker-compose.testing.azure.yaml
      dockerComposeFileArgs: ${{ parameters.composeArgs }}
      qualifyImageNames: true

  - task: DockerCompose@0
    displayName: Run tests
    inputs:
      action: Run a Docker Compose command
      containerregistrytype: Container Registry
      dockerComposeFile: docker-compose.yaml
      additionalDockerComposeFiles: docker-compose.testing.azure.yaml
      serviceName: pyspawn
      dockerComposeCommand: run --rm pyspawn
      dockerComposeFileArgs: ${{ parameters.composeArgs }}
      qualifyImageNames: true

  - task: PublishTestResults@2
    displayName: "Publish test results"
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "**/xunit-result-all.xml"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish coverage reports"
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage-reports/coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage-reports/"

  - task: DockerCompose@0
    displayName: Compose down
    inputs:
      action: Run a Docker Compose command
      containerregistrytype: Container Registry
      dockerComposeFile: docker-compose.yaml
      additionalDockerComposeFiles: docker-compose.testing.azure.yaml
      serviceName: pyspawn
      dockerComposeCommand: down
      dockerComposeFileArgs: ${{ parameters.composeArgs }}